clean <- function(df) {
  within(df, {
    Product_Info_1 <- as.factor(Product_Info_1)
    Product_Info_2 <- as.factor(Product_Info_2)
    Product_Info_3 <- as.factor(Product_Info_3)
    Product_Info_5 <- as.factor(Product_Info_5)
    Product_Info_6 <- as.factor(Product_Info_6)
    Product_Info_7 <- as.factor(Product_Info_7)
    Employment_Info_2 <- as.factor(Employment_Info_2)
    Employment_Info_3 <- as.factor(Employment_Info_3)
    Employment_Info_5 <- as.factor(Employment_Info_5)
    InsuredInfo_1 <- as.factor(InsuredInfo_1)
    InsuredInfo_2 <- as.factor(InsuredInfo_2)
    InsuredInfo_3 <- as.factor(InsuredInfo_3)
    InsuredInfo_4 <- as.factor(InsuredInfo_4)
    InsuredInfo_5 <- as.factor(InsuredInfo_5)
    InsuredInfo_6 <- as.factor(InsuredInfo_6)
    InsuredInfo_7 <- as.factor(InsuredInfo_7)
    Insurance_History_1 <- as.factor(Insurance_History_1)
    Insurance_History_2 <- as.factor(Insurance_History_2)
    Insurance_History_3 <- as.factor(Insurance_History_3)
    Insurance_History_4 <- as.factor(Insurance_History_4)
    Insurance_History_7 <- as.factor(Insurance_History_7)
    Insurance_History_8 <- as.factor(Insurance_History_8)
    Insurance_History_9 <- as.factor(Insurance_History_9)
    Family_Hist_1 <- as.factor(Family_Hist_1)
    Medical_History_2 <- as.factor(Medical_History_2)
    Medical_History_3 <- as.factor(Medical_History_3)
    Medical_History_4 <- as.factor(Medical_History_4)
    Medical_History_5 <- as.factor(Medical_History_5)
    Medical_History_6 <- as.factor(Medical_History_6)
    Medical_History_7 <- as.factor(Medical_History_7)
    Medical_History_8 <- as.factor(Medical_History_8)
    Medical_History_9 <- as.factor(Medical_History_9)
    Medical_History_11 <- as.factor(Medical_History_11)
    Medical_History_12 <- as.factor(Medical_History_12)
    Medical_History_13 <- as.factor(Medical_History_13)
    Medical_History_14 <- as.factor(Medical_History_14)
    Medical_History_16 <- as.factor(Medical_History_16)
    Medical_History_17 <- as.factor(Medical_History_17)
    Medical_History_18 <- as.factor(Medical_History_18)
    Medical_History_19 <- as.factor(Medical_History_19)
    Medical_History_20 <- as.factor(Medical_History_20)
    Medical_History_21 <- as.factor(Medical_History_21)
    Medical_History_22 <- as.factor(Medical_History_22)
    Medical_History_23 <- as.factor(Medical_History_23)
    Medical_History_25 <- as.factor(Medical_History_25)
    Medical_History_26 <- as.factor(Medical_History_26)
    Medical_History_27 <- as.factor(Medical_History_27)
    Medical_History_28 <- as.factor(Medical_History_28)
    Medical_History_29 <- as.factor(Medical_History_29)
    Medical_History_30 <- as.factor(Medical_History_30)
    Medical_History_31 <- as.factor(Medical_History_31)
    Medical_History_33 <- as.factor(Medical_History_33)
    Medical_History_34 <- as.factor(Medical_History_34)
    Medical_History_35 <- as.factor(Medical_History_35)
    Medical_History_36 <- as.factor(Medical_History_36)
    Medical_History_37 <- as.factor(Medical_History_37)
    Medical_History_38 <- as.factor(Medical_History_38)
    Medical_History_39 <- as.factor(Medical_History_39)
    Medical_History_40 <- as.factor(Medical_History_40)
    Medical_History_41 <- as.factor(Medical_History_41)
  })
}

train <- read.csv("train.csv") |>
  clean()
test <- read.csv("test.csv") |>
  clean()
